version: 1.0.{build}.*
skip_non_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: detailed
artifacts:
- path: '**\*.nupkg'
  name: nupkg
deploy:
- provider: GitHub
  auth_token:
    secure: UKi94d2MuFkTQQi/a/fCIk77vNm1Iqi90f7PkeJKs8HVvCuGGhxlqNKKblKL6iL+
  artifact: nupkg
  draft: true
  force_update: true
