version: 1.0.{build}.0
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  parallel: true
  verbosity: detailed
artifacts:
- path: '**\*.nupkg'
  name: nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 4MlQhgnX8YAri6kuhFp+qpwb8s2vk21yFFnfcsPiprPCmLA8WeAALO0Iu2FRjwS7
  skip_symbols: true
  artifact: nupkg
- provider: GitHub
  auth_token:
    secure: s1axn0765Y8aLo2y9eqsAbDD+fFk9sNyXi+btYt26U/eaxLP0wPQruYBNRmz/oe3
  artifact: nupkg
  force_update: true
notifications:
- provider: Email
  to:
  - ennerperez@gmail.com
  subject: AppVeyor Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
